apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-actions
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: github-actions
rules:
- apiGroups:
  - apps
  - batch
  resources:
  - "*"
  verbs:
  - "get"
  - "list"
  - "watch"
  - "create"
  - "update"
  - "patch"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: github-actions
subjects:
- kind: ServiceAccount
  name: github-actions
roleRef:
  kind: Role
  name: github-actions
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: github-actions
  annotations:
    kubernetes.io/service-account.name: "github-actions"