name: Build Docker COntainer & Push to image repository

on:
  workflow_call:
  workflow_dispatch:
  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_django_job:
    uses: przemaj1990/djnago-k8s/.github/workflows/test-django.yaml@main
  build:
    runs-on: ubuntu-latest
    needs: [test_django_job]
    env:
      DJANGO_SECRET_KEY: test-key-not-good-maybe-make-one-better
      CLUSTER_NAME: 54.195.23.135
    steps:
    - name:  Checkout code.
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Get short SHA
      uses: benjlevesque/short-sha@v2.1
      id: short-sha
      with:
        length: 6
    - name: Build container image
      working-directory: dev/django-k8s/web
      run: |
        docker build -f Dockerfile \
          -t docker.io/przemaj1990/django-k8s:latest \
          -t docker.io/przemaj1990/django-k8s:${{ steps.short-sha.outputs.sha }} \
          .
    - name: Push image
      run: |
        docker push docker.io/przemaj1990/django-k8s --all-tags
    - name: test conntection to k8s
      uses: myrotvorets/kubectl-action@2.0.0
      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        version: latest
        args: --insecure-skip-tls-verify get pods
    - name: Update Deployemnt Image
      uses: myrotvorets/kubectl-action@2.0.0
      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        version: latest
        args: --insecure-skip-tls-verify set image deployment/django-k8s-web-deployment django-k8s-web=docker.io/przemaj1990/django-k8s:${{ steps.short-sha.outputs.sha }}
    - name: Wait for rollout to finish
      uses: myrotvorets/kubectl-action@2.0.0
      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        version: latest
        args: --insecure-skip-tls-verify rollout status deployment/django-k8s-web-deployment
    - name: Run Migration
      uses: myrotvorets/kubectl-action@2.0.0
      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        version: latest
        args: --insecure-skip-tls-verify exec -it $(kubectl get pod -l=app=django-k8s-web-deployment -o NAME | tail -n 1) -- bash /app/migrate.sh
        continue-on-error: true
        run: |
          exit 1
