name: Build Docker COntainer & Push to image repository

on:
  workflow_call:
  workflow_dispatch:
  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_django_job:
    uses: przemaj1990/djnago-k8s/.github/workflows/test-django.yaml@main
  build:
    runs-on: ubuntu-latest
    needs: [test_django_job]
    env:
      DJANGO_SECRET_KEY: test-key-not-good-maybe-make-one-better
      CLUSTER_NAME: 54.195.23.135
    steps:
    - name:  Checkout code.
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Get short SHA
      uses: benjlevesque/short-sha@v2.1
      id: short-sha
      with:
        length: 6
    - name: Build container image
      working-directory: dev/django-k8s/web
      run: |
        docker build -f Dockerfile \
          -t docker.io/przemaj1990/django-k8s:latest \
          -t docker.io/przemaj1990/django-k8s:${{ steps.short-sha.outputs.sha }} \
          .
    - name: Push image
      run: |
        docker push docker.io/przemaj1990/django-k8s --all-tags
    - name: Update secrets
      run: |
        cat << EOF >> dev/django-k8s/web/.env.new
        DEBUG=1
        REGION=texas
        DJANGO_SUPERUSER_USERNAME=${{ secrets.DJANGO_SUPERUSER_USERNAME }}
        DJANGO_SUPERUSER_PASSWORD=${{ secrets.DJANGO_SUPERUSER_PASSWORD }}
        DJANGO_SUERPUSER_EMAIL=${{ secrets.DJANGO_SUERPUSER_EMAIL }}
        DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}
        ENV_ALLOW_HOST=${{ secrets.ENV_ALLOW_HOST }}
        DB_IGNORE_SSL=t${{ secrets.DB_IGNORE_SSL }}rue
        POSTGRES_READY=${{ secrets.POSTGRES_READY }}
        POSTGRES_DB=${{ secrets.POSTGRES_DB }}
        POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_USER=${{ secrets.POSTGRES_USER }}
        POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
        POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
        EOF
    - name: Update Secret 1
      uses: myrotvorets/kubectl-action@2.0.0
      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        version: latest
        args: --insecure-skip-tls-verify delete secret django-k8s-web-prod-env
    - name: Update Secret 2
      uses: myrotvorets/kubectl-action@2.0.0
      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        version: latest
        args: --insecure-skip-tls-verify create secret generic django-k8s-web-prod-env --from-env-file=dev/django-k8s/web/.env.new
    - name: Update Deployemnt Image
      uses: myrotvorets/kubectl-action@2.0.0
      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        version: latest
        args: --insecure-skip-tls-verify set image deployment/django-k8s-web-deployment django-k8s-web=docker.io/przemaj1990/django-k8s:${{ steps.short-sha.outputs.sha }}
    - name: Wait for rollout to finish
      uses: myrotvorets/kubectl-action@2.0.0
      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        version: latest
        args: --insecure-skip-tls-verify rollout status deployment/django-k8s-web-deployment
    - name: Run Migration
      uses: myrotvorets/kubectl-action@2.0.0
      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        version: latest
        run: --insecure-skip-tls-verify exec -it $(kubectl get pod -l app=django-k8s-web-deployment -o NAME | tail -n 1) -- bash /app/migrate.sh
