name: Build Docker COntainer & Push to image repository

on:
  workflow_call:
  workflow_dispatch:
  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_django:
    uses: przemaj1990/djnago-k8s/.github/workflow/test-django.yaml@main
  docker_build:
    runs-on: ubuntu-latest
    env:
      DJANGO_SECRET_KEY: test-key-not-good-maybe-make-one-better
    steps:
    - uses: actions/checkout@v2