name: Build Docker COntainer & Push to image repository

on:
  workflow_call:
  workflow_dispatch:
  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_django_job:
    uses: przemaj1990/djnago-k8s/.github/workflows/test-django.yaml@main
  build:
    runs-on: ubuntu-latest
    needs: [test_django_job]
    env:
      DJANGO_SECRET_KEY: test-key-not-good-maybe-make-one-better
      CLUSTER_NAME: 54.195.23.135
    steps:
    - name:  Checkout code.
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Get short SHA
      uses: benjlevesque/short-sha@v2.1
      id: short-sha
      with:
        length: 6
    - name: Build container image
      working-directory: dev/django-k8s/web
      run: |
        docker build -f Dockerfile \
          -t docker.io/przemaj1990/django-k8s:latest \
          -t docker.io/przemaj1990/django-k8s:${{ steps.short-sha.outputs.sha }} \
          .
    - name: Push image
      run: |
        docker push docker.io/przemaj1990/django-k8s --all-tags
    - name: test conntection to k8s
      uses: myrotvorets/kubectl-action@2.0.0
      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        version: latest
        args: --insecure-skip-tls-verify get pods
    - name: Update secrets
      uses: tale/kubectl-action@v1
      with:
        base64-kube-config: ${{ secrets.KUBE_CONFIG_DATA }}
        run: |
          cat << EOF >> dev/django-k8s/web/.env
          DEBUG=1
          REGION=texas
          DJANGO_SUPERUSER_USERNAME=admin
          DJANGO_SUPERUSER_PASSWORD=mydjangopw
          DJANGO_SUERPUSER_EMAIL=przemaj1990@gmail.com
          DJANGO_SECRET_KEY=1j9*q=8275dm#qxv8^iz#debt@dk57cpk9&7xk%us^&^s(02g5

          ENV_ALLOW_HOST="*"

          DB_IGNORE_SSL=true
          POSTGRES_READY=0
          POSTGRES_DB=dockerdc
          POSTGRES_PASSWORD=mysecretpassword
          POSTGRES_USER=myuser
          POSTGRES_HOST=postgres
          POSTGRES_PORT=5432
          EOF
          kubectl delete secret django-k8s-web-prod-env
          kubectl create secret generic django-k8s-web-prod-env --from-env-file=dev/django-k8s/web/.env
    - name: Update Deployemnt Image
      uses: myrotvorets/kubectl-action@2.0.0
      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        version: latest
        args: --insecure-skip-tls-verify set image deployment/django-k8s-web-deployment django-k8s-web=docker.io/przemaj1990/django-k8s:${{ steps.short-sha.outputs.sha }}
    - name: Wait for rollout to finish
      uses: myrotvorets/kubectl-action@2.0.0
      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        version: latest
        args: --insecure-skip-tls-verify rollout status deployment/django-k8s-web-deployment
    - name: Run Migration
      uses: tale/kubectl-action@v1
      with:
        base64-kube-config: ${{ secrets.KUBE_CONFIG_DATA }}
        run: --insecure-skip-tls-verify exec -it $(kubectl get pod -l app=django-k8s-web-deployment -o NAME | tail -n 1) -- bash /app/migrate.sh
